//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.27 at 04:31:45 PM CST 
//


package cn.explink.b2c.vipshop.oxo.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for response element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="response">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="head">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="response_time">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;enumeration value="2013-01-31 11:22:25"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                     &lt;element name="cust_code">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;enumeration value="NHLDP004"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                     &lt;element name="sys_response_code">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;enumeration value="S00"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                     &lt;element name="sys_respnose_msg">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;enumeration value="SUCCESS"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="orders">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="order" maxOccurs="unbounded">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="brand_name">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="nike"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element name="store_name">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="��ѹ㳡��"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element name="store_contacts">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="����"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element name="store_tel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="cnor_prov">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="�㶫"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element name="cnor_city">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="����"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element name="cnor_region">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="�����"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element name="cnor_addr">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="xxxxx"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element name="required_time">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="2015-04-22 11:06:00"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element name="order_sn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="buyer_name">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="����"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element name="buyer_address">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="����·22��"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element name="mobile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="goods_money" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="money" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="is_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="ext_pay_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="post_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="total_pack" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="original_weight" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="original_volume" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="warehouse">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="VIP_NH"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element name="customer_name">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="���?˾"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element name="sales_platform">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="ΨƷ��"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element name="transport_type">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="3CС�ҵ�"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element name="valuation_value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="warehouse_addr">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="�㶫ʡ�����д���"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element name="freight" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="cmd_type">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="new"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element name="business_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="org_name">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="��Զ-����վ"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element name="org_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="cust_order_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="tel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "head",
    "orders"
})
@XmlRootElement(name = "response")
public class TpsOrderVo {

    @XmlElement(required = true)
    protected TpsOrderVo.Head head;
    @XmlElement(required = true)
    protected TpsOrderVo.Orders orders;

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link TpsOrderVo.Head }
     *     
     */
    public TpsOrderVo.Head getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpsOrderVo.Head }
     *     
     */
    public void setHead(TpsOrderVo.Head value) {
        this.head = value;
    }

    /**
     * Gets the value of the orders property.
     * 
     * @return
     *     possible object is
     *     {@link TpsOrderVo.Orders }
     *     
     */
    public TpsOrderVo.Orders getOrders() {
        return orders;
    }

    /**
     * Sets the value of the orders property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpsOrderVo.Orders }
     *     
     */
    public void setOrders(TpsOrderVo.Orders value) {
        this.orders = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="response_time">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="2013-01-31 11:22:25"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="cust_code">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="NHLDP004"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="sys_response_code">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="S00"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="sys_respnose_msg">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="SUCCESS"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "version",
        "responseTime",
        "custCode",
        "sysResponseCode",
        "sysRespnoseMsg"
    })
    public static class Head {

        @XmlElement(required = true)
        protected String version;
        @XmlElement(name = "response_time", required = true)
        protected String responseTime;
        @XmlElement(name = "cust_code", required = true)
        protected String custCode;
        @XmlElement(name = "sys_response_code", required = true)
        protected String sysResponseCode;
        @XmlElement(name = "sys_respnose_msg", required = true)
        protected String sysRespnoseMsg;

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

        /**
         * Gets the value of the responseTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResponseTime() {
            return responseTime;
        }

        /**
         * Sets the value of the responseTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResponseTime(String value) {
            this.responseTime = value;
        }

        /**
         * Gets the value of the custCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustCode() {
            return custCode;
        }

        /**
         * Sets the value of the custCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustCode(String value) {
            this.custCode = value;
        }

        /**
         * Gets the value of the sysResponseCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSysResponseCode() {
            return sysResponseCode;
        }

        /**
         * Sets the value of the sysResponseCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSysResponseCode(String value) {
            this.sysResponseCode = value;
        }

        /**
         * Gets the value of the sysRespnoseMsg property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSysRespnoseMsg() {
            return sysRespnoseMsg;
        }

        /**
         * Sets the value of the sysRespnoseMsg property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSysRespnoseMsg(String value) {
            this.sysRespnoseMsg = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="order" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="brand_name">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="nike"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="store_name">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="��ѹ㳡��"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="store_contacts">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="����"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="store_tel" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="cnor_prov">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="�㶫"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="cnor_city">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="����"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="cnor_region">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="�����"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="cnor_addr">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="xxxxx"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="required_time">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="2015-04-22 11:06:00"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="order_sn" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="buyer_name">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="����"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="buyer_address">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="����·22��"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="mobile" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="goods_money" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="money" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="is_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ext_pay_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="post_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="total_pack" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="original_weight" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="original_volume" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="warehouse">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="VIP_NH"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="customer_name">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="���?˾"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="sales_platform">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="ΨƷ��"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="transport_type">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="3CС�ҵ�"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="valuation_value" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="warehouse_addr">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="�㶫ʡ�����д���"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="freight" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="cmd_type">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="new"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="business_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="org_name">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="��Զ-����վ"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="org_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="cust_order_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="tel" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "order"
    })
    public static class Orders {

        @XmlElement(required = true)
        protected List<TpsOrderVo.Orders.Order> order;

        /**
         * Gets the value of the order property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the order property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOrder().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TpsOrderVo.Orders.Order }
         * 
         * 
         */
        public List<TpsOrderVo.Orders.Order> getOrder() {
            if (order == null) {
                order = new ArrayList<TpsOrderVo.Orders.Order>();
            }
            return this.order;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="brand_name">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="nike"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="store_name">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="��ѹ㳡��"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="store_contacts">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="����"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="store_tel" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="cnor_prov">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="�㶫"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="cnor_city">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="����"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="cnor_region">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="�����"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="cnor_addr">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="xxxxx"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="required_time">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="2015-04-22 11:06:00"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="order_sn" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="buyer_name">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="����"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="buyer_address">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="����·22��"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="mobile" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="goods_money" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="money" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="is_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ext_pay_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="post_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="total_pack" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="original_weight" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="original_volume" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="warehouse">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="VIP_NH"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="customer_name">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="���?˾"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="sales_platform">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="ΨƷ��"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="transport_type">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="3CС�ҵ�"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="valuation_value" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="warehouse_addr">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="�㶫ʡ�����д���"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="freight" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="cmd_type">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="new"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="business_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="org_name">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="��Զ-����վ"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="org_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="cust_order_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="tel" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "brandName",
            "storeName",
            "storeContacts",
            "storeTel",
            "cnorProv",
            "cnorCity",
            "cnorRegion",
            "cnorAddr",
            "requiredTime",
            "orderSn",
            "buyerName",
            "buyerAddress",
            "mobile",
            "goodsMoney",
            "money",
            "isCode",
            "extPayType",
            "postCode",
            "totalPack",
            "originalWeight",
            "originalVolume",
            "warehouse",
            "customerName",
            "salesPlatform",
            "transportType",
            "valuationValue",
            "warehouseAddr",
            "freight",
            "cmdType",
            "businessType",
            "orgName",
            "orgCode",
            "custOrderNo",
            "tel"
        })
        public static class Order {

            @XmlElement(required = true)
            protected String id;
            @XmlElement(name = "brand_name", required = true)
            protected String brandName;
            @XmlElement(name = "store_name", required = true)
            protected String storeName;
            @XmlElement(name = "store_contacts", required = true)
            protected String storeContacts;
            @XmlElement(name = "store_tel", required = true)
            protected String storeTel;
            @XmlElement(name = "cnor_prov", required = true)
            protected String cnorProv;
            @XmlElement(name = "cnor_city", required = true)
            protected String cnorCity;
            @XmlElement(name = "cnor_region", required = true)
            protected String cnorRegion;
            @XmlElement(name = "cnor_addr", required = true)
            protected String cnorAddr;
            @XmlElement(name = "required_time", required = true)
            protected String requiredTime;
            @XmlElement(name = "order_sn", required = true)
            protected String orderSn;
            @XmlElement(name = "buyer_name", required = true)
            protected String buyerName;
            @XmlElement(name = "buyer_address", required = true)
            protected String buyerAddress;
            @XmlElement(required = true)
            protected String mobile;
            @XmlElement(name = "goods_money", required = true)
            protected String goodsMoney;
            @XmlElement(required = true)
            protected String money;
            @XmlElement(name = "is_code", required = true)
            protected String isCode;
            @XmlElement(name = "ext_pay_type", required = true)
            protected String extPayType;
            @XmlElement(name = "post_code", required = true)
            protected String postCode;
            @XmlElement(name = "total_pack", required = true)
            protected String totalPack;
            @XmlElement(name = "original_weight", required = true)
            protected String originalWeight;
            @XmlElement(name = "original_volume", required = true)
            protected String originalVolume;
            @XmlElement(required = true)
            protected String warehouse;
            @XmlElement(name = "customer_name", required = true)
            protected String customerName;
            @XmlElement(name = "sales_platform", required = true)
            protected String salesPlatform;
            @XmlElement(name = "transport_type", required = true)
            protected String transportType;
            @XmlElement(name = "valuation_value", required = true)
            protected String valuationValue;
            @XmlElement(name = "warehouse_addr", required = true)
            protected String warehouseAddr;
            @XmlElement(required = true)
            protected String freight;
            @XmlElement(name = "cmd_type", required = true)
            protected String cmdType;
            @XmlElement(name = "business_type", required = true)
            protected String businessType;
            @XmlElement(name = "org_name", required = true)
            protected String orgName;
            @XmlElement(name = "org_code", required = true)
            protected String orgCode;
            @XmlElement(name = "cust_order_no", required = true)
            protected String custOrderNo;
            @XmlElement(required = true)
            protected String tel;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the brandName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBrandName() {
                return brandName;
            }

            /**
             * Sets the value of the brandName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBrandName(String value) {
                this.brandName = value;
            }

            /**
             * Gets the value of the storeName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStoreName() {
                return storeName;
            }

            /**
             * Sets the value of the storeName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStoreName(String value) {
                this.storeName = value;
            }

            /**
             * Gets the value of the storeContacts property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStoreContacts() {
                return storeContacts;
            }

            /**
             * Sets the value of the storeContacts property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStoreContacts(String value) {
                this.storeContacts = value;
            }

            /**
             * Gets the value of the storeTel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStoreTel() {
                return storeTel;
            }

            /**
             * Sets the value of the storeTel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStoreTel(String value) {
                this.storeTel = value;
            }

            /**
             * Gets the value of the cnorProv property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCnorProv() {
                return cnorProv;
            }

            /**
             * Sets the value of the cnorProv property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCnorProv(String value) {
                this.cnorProv = value;
            }

            /**
             * Gets the value of the cnorCity property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCnorCity() {
                return cnorCity;
            }

            /**
             * Sets the value of the cnorCity property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCnorCity(String value) {
                this.cnorCity = value;
            }

            /**
             * Gets the value of the cnorRegion property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCnorRegion() {
                return cnorRegion;
            }

            /**
             * Sets the value of the cnorRegion property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCnorRegion(String value) {
                this.cnorRegion = value;
            }

            /**
             * Gets the value of the cnorAddr property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCnorAddr() {
                return cnorAddr;
            }

            /**
             * Sets the value of the cnorAddr property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCnorAddr(String value) {
                this.cnorAddr = value;
            }

            /**
             * Gets the value of the requiredTime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequiredTime() {
                return requiredTime;
            }

            /**
             * Sets the value of the requiredTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequiredTime(String value) {
                this.requiredTime = value;
            }

            /**
             * Gets the value of the orderSn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOrderSn() {
                return orderSn;
            }

            /**
             * Sets the value of the orderSn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOrderSn(String value) {
                this.orderSn = value;
            }

            /**
             * Gets the value of the buyerName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBuyerName() {
                return buyerName;
            }

            /**
             * Sets the value of the buyerName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBuyerName(String value) {
                this.buyerName = value;
            }

            /**
             * Gets the value of the buyerAddress property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBuyerAddress() {
                return buyerAddress;
            }

            /**
             * Sets the value of the buyerAddress property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBuyerAddress(String value) {
                this.buyerAddress = value;
            }

            /**
             * Gets the value of the mobile property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMobile() {
                return mobile;
            }

            /**
             * Sets the value of the mobile property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMobile(String value) {
                this.mobile = value;
            }

            /**
             * Gets the value of the goodsMoney property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGoodsMoney() {
                return goodsMoney;
            }

            /**
             * Sets the value of the goodsMoney property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGoodsMoney(String value) {
                this.goodsMoney = value;
            }

            /**
             * Gets the value of the money property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMoney() {
                return money;
            }

            /**
             * Sets the value of the money property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMoney(String value) {
                this.money = value;
            }

            /**
             * Gets the value of the isCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIsCode() {
                return isCode;
            }

            /**
             * Sets the value of the isCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIsCode(String value) {
                this.isCode = value;
            }

            /**
             * Gets the value of the extPayType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExtPayType() {
                return extPayType;
            }

            /**
             * Sets the value of the extPayType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExtPayType(String value) {
                this.extPayType = value;
            }

            /**
             * Gets the value of the postCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPostCode() {
                return postCode;
            }

            /**
             * Sets the value of the postCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPostCode(String value) {
                this.postCode = value;
            }

            /**
             * Gets the value of the totalPack property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTotalPack() {
                return totalPack;
            }

            /**
             * Sets the value of the totalPack property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTotalPack(String value) {
                this.totalPack = value;
            }

            /**
             * Gets the value of the originalWeight property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOriginalWeight() {
                return originalWeight;
            }

            /**
             * Sets the value of the originalWeight property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOriginalWeight(String value) {
                this.originalWeight = value;
            }

            /**
             * Gets the value of the originalVolume property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOriginalVolume() {
                return originalVolume;
            }

            /**
             * Sets the value of the originalVolume property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOriginalVolume(String value) {
                this.originalVolume = value;
            }

            /**
             * Gets the value of the warehouse property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getWarehouse() {
                return warehouse;
            }

            /**
             * Sets the value of the warehouse property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWarehouse(String value) {
                this.warehouse = value;
            }

            /**
             * Gets the value of the customerName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCustomerName() {
                return customerName;
            }

            /**
             * Sets the value of the customerName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCustomerName(String value) {
                this.customerName = value;
            }

            /**
             * Gets the value of the salesPlatform property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSalesPlatform() {
                return salesPlatform;
            }

            /**
             * Sets the value of the salesPlatform property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSalesPlatform(String value) {
                this.salesPlatform = value;
            }

            /**
             * Gets the value of the transportType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTransportType() {
                return transportType;
            }

            /**
             * Sets the value of the transportType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTransportType(String value) {
                this.transportType = value;
            }

            /**
             * Gets the value of the valuationValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValuationValue() {
                return valuationValue;
            }

            /**
             * Sets the value of the valuationValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValuationValue(String value) {
                this.valuationValue = value;
            }

            /**
             * Gets the value of the warehouseAddr property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getWarehouseAddr() {
                return warehouseAddr;
            }

            /**
             * Sets the value of the warehouseAddr property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWarehouseAddr(String value) {
                this.warehouseAddr = value;
            }

            /**
             * Gets the value of the freight property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFreight() {
                return freight;
            }

            /**
             * Sets the value of the freight property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFreight(String value) {
                this.freight = value;
            }

            /**
             * Gets the value of the cmdType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCmdType() {
                return cmdType;
            }

            /**
             * Sets the value of the cmdType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCmdType(String value) {
                this.cmdType = value;
            }

            /**
             * Gets the value of the businessType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBusinessType() {
                return businessType;
            }

            /**
             * Sets the value of the businessType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBusinessType(String value) {
                this.businessType = value;
            }

            /**
             * Gets the value of the orgName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOrgName() {
                return orgName;
            }

            /**
             * Sets the value of the orgName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOrgName(String value) {
                this.orgName = value;
            }

            /**
             * Gets the value of the orgCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOrgCode() {
                return orgCode;
            }

            /**
             * Sets the value of the orgCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOrgCode(String value) {
                this.orgCode = value;
            }

            /**
             * Gets the value of the custOrderNo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCustOrderNo() {
                return custOrderNo;
            }

            /**
             * Sets the value of the custOrderNo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCustOrderNo(String value) {
                this.custOrderNo = value;
            }

            /**
             * Gets the value of the tel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTel() {
                return tel;
            }

            /**
             * Sets the value of the tel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTel(String value) {
                this.tel = value;
            }

        }

    }

}
