//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.31 at 10:06:09 AM CST 
//


package cn.explink.b2c.vipshop.oxo.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for response element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="response">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="head">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                     &lt;element name="request_time">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;enumeration value="2015-04-15 21:20:23"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                     &lt;element name="cust_code">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;enumeration value="FY"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                     &lt;element name="sys_response_code">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;enumeration value="S00"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                     &lt;element name="sys_respnose_msg">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;enumeration value="SUCCESS"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="binds">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="bind" maxOccurs="unbounded">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *                               &lt;element name="transport_no" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *                               &lt;element name="operator">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="����"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element name="operater_time">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="2015-04-16 21:20:23"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element name="operater_type" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *                               &lt;element name="remark">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="ȡ���ɹ�"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "head",
    "binds"
})
@XmlRootElement(name = "response")
public class TpsOxoPickStateVo {

    @XmlElement(required = true)
    protected TpsOxoPickStateVo.Head head;
    @XmlElement(required = true)
    protected TpsOxoPickStateVo.Binds binds;

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link TpsOxoPickStateVo.Head }
     *     
     */
    public TpsOxoPickStateVo.Head getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpsOxoPickStateVo.Head }
     *     
     */
    public void setHead(TpsOxoPickStateVo.Head value) {
        this.head = value;
    }

    /**
     * Gets the value of the binds property.
     * 
     * @return
     *     possible object is
     *     {@link TpsOxoPickStateVo.Binds }
     *     
     */
    public TpsOxoPickStateVo.Binds getBinds() {
        return binds;
    }

    /**
     * Sets the value of the binds property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpsOxoPickStateVo.Binds }
     *     
     */
    public void setBinds(TpsOxoPickStateVo.Binds value) {
        this.binds = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="bind" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}String"/>
     *                   &lt;element name="transport_no" type="{http://www.w3.org/2001/XMLSchema}String"/>
     *                   &lt;element name="operator">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="����"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="operater_time">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="2015-04-16 21:20:23"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="operater_type" type="{http://www.w3.org/2001/XMLSchema}String"/>
     *                   &lt;element name="remark">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="ȡ���ɹ�"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bind"
    })
    public static class Binds {

        @XmlElement(required = true)
        protected List<TpsOxoPickStateVo.Binds.Bind> bind;

        /**
         * Gets the value of the bind property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the bind property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBind().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TpsOxoPickStateVo.Binds.Bind }
         * 
         * 
         */
        public List<TpsOxoPickStateVo.Binds.Bind> getBind() {
            if (bind == null) {
                bind = new ArrayList<TpsOxoPickStateVo.Binds.Bind>();
            }
            return this.bind;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}String"/>
         *         &lt;element name="transport_no" type="{http://www.w3.org/2001/XMLSchema}String"/>
         *         &lt;element name="operator">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="����"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="operater_time">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="2015-04-16 21:20:23"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="operater_type" type="{http://www.w3.org/2001/XMLSchema}String"/>
         *         &lt;element name="remark">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="ȡ���ɹ�"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "transportNo",
            "operator",
            "operaterTime",
            "operaterType",
            "remark"
        })
        public static class Bind {

            protected String id;
            @XmlElement(name = "transport_no")
            protected String transportNo;
            @XmlElement(required = true)
            protected String operator;
            @XmlElement(name = "operater_time", required = true)
            protected String operaterTime;
            @XmlElement(name = "operater_type")
            protected String operaterType;
            @XmlElement(required = true)
            protected String remark;

            /**
             * Gets the value of the id property.
             * 
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the transportNo property.
             * 
             */
            public String getTransportNo() {
                return transportNo;
            }

            /**
             * Sets the value of the transportNo property.
             * 
             */
            public void setTransportNo(String value) {
                this.transportNo = value;
            }

            /**
             * Gets the value of the operator property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOperator() {
                return operator;
            }

            /**
             * Sets the value of the operator property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOperator(String value) {
                this.operator = value;
            }

            /**
             * Gets the value of the operaterTime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOperaterTime() {
                return operaterTime;
            }

            /**
             * Sets the value of the operaterTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOperaterTime(String value) {
                this.operaterTime = value;
            }

            /**
             * Gets the value of the operaterType property.
             * 
             */
            public String getOperaterType() {
                return operaterType;
            }

            /**
             * Sets the value of the operaterType property.
             * 
             */
            public void setOperaterType(String value) {
                this.operaterType = value;
            }

            /**
             * Gets the value of the remark property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRemark() {
                return remark;
            }

            /**
             * Sets the value of the remark property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRemark(String value) {
                this.remark = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="request_time">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="2015-04-15 21:20:23"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="cust_code">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="FY"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="sys_response_code">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="S00"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="sys_respnose_msg">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="SUCCESS"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "version",
        "requestTime",
        "custCode",
        "sysResponseCode",
        "sysRespnoseMsg"
    })
    public static class Head {

        @XmlElement(required = true)
        protected String version;
        @XmlElement(name = "request_time", required = true)
        protected String requestTime;
        @XmlElement(name = "cust_code", required = true)
        protected String custCode;
        @XmlElement(name = "sys_response_code", required = true)
        protected String sysResponseCode;
        @XmlElement(name = "sys_respnose_msg", required = true)
        protected String sysRespnoseMsg;

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

        /**
         * Gets the value of the requestTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequestTime() {
            return requestTime;
        }

        /**
         * Sets the value of the requestTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRequestTime(String value) {
            this.requestTime = value;
        }

        /**
         * Gets the value of the custCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustCode() {
            return custCode;
        }

        /**
         * Sets the value of the custCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustCode(String value) {
            this.custCode = value;
        }

        /**
         * Gets the value of the sysResponseCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSysResponseCode() {
            return sysResponseCode;
        }

        /**
         * Sets the value of the sysResponseCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSysResponseCode(String value) {
            this.sysResponseCode = value;
        }

        /**
         * Gets the value of the sysRespnoseMsg property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSysRespnoseMsg() {
            return sysRespnoseMsg;
        }

        /**
         * Sets the value of the sysRespnoseMsg property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSysRespnoseMsg(String value) {
            this.sysRespnoseMsg = value;
        }

    }

}
