
package cn.explink.b2c.auto.order.vo;

import java.math.BigDecimal;
import java.util.List;

/**
 * InfCarrierPickTaskSend generated by hbm2java
 */

public class TPSOrder {

    private Integer infCarrierPickTaskSendId;

    private Long recordVersion;

    /**
     * 收件人地址
     */
    private String buyerAddress;

    /**
     * 电话
     */
    private String tel;

    /**
     * 手机号码
     */
    private String mobile;

    /**
     * 邮编
     */
    private String postCode;

    /**
     * 重量
     */
    private BigDecimal originalWeight;

    /**
     * 体积
     */
    private BigDecimal originalVolume;

    /**
     * 所属仓库
     */
    private String warehouse;

    /**
     * 总箱数
     */
    private Integer totalPack;

    /**
     * 订单客户
     */
    private String customerName;

    /**
     * 销售平台
     */
    private String salesPlatform;

    /**
     * 运输类型
     */
    private String transportType;

    /**
     * 保价价值
     */
    private BigDecimal valuationValue;

    /**
     * 唯品会仓库地址
     */
    private String warehouseAddr;

    /**
     * 运费
     */
    private BigDecimal feight;

    /**
     * 操作指令
     */
    private String cmdType;

    /**
     * 业务类型
     */
    private Integer businessType;

    /**
     * 是否已发送
     */
    private boolean isSend;

    /**
     * 品牌供应商
     */
    private String brandName;

    /**
     * 提货门店
     */
    private String storeName;

    /**
     * 发货省
     */
    private String cnorProv;

    /**
     * 发货城市
     */
    private String cnorCity;

    /**
     * 发货区
     */
    private String cnorRegion;

    /**
     * 发货相信地址
     */
    private String cnorAddr;

    /**
     * 要求提货时间
     */
    private String requiredTime;

    /**
     * 承运商编码
     */
    private String custCode;

    /**
     * 订单号
     */
    private String orderSn;

    /**
     * 收件人
     */
    private String buyerName;

    /**
     * 门店联系人
     */
    private String storeContacts;

    /**
     * 门店联系方式
     */
    private String storeTel;

    /**
     * TMS订单号
     */
    private String custOrderNo;

    /**
     * 提货站点名称
     */
    private String orgName;

    /**
     * 提货站点编码
     */
    private String orgCode;

    /**
     * 商品金额
     */
    private BigDecimal orderSum;

    /**
     * 代收金额
     */
    private BigDecimal codAmount;

    /**
     * 是否货到付款
     */
    private boolean isCod;

    /**
     * 扩展支付方式
     */
    private Integer payment;

    // 出仓时间
    private Long addTime;
    
    //记录生成时间
    private Long createTime;

    // 箱号
    private String boxNo;

    // 团购标识
    private String vipClub;

    // 服务类型
    private Integer serviceType;

    // 订单配送批次
    private String orderDeliveryBatch;

    // 建议最晚揽收时间
    private Long lastFetchTime;

    // 预约上门揽退时间
    private String goGetReturnTime;

    // 要求送货时间
    private String transportDay;
    
    //是否集包
    private Integer isGatherpack;
    
    //最后一箱
    private Integer isGathercomp;
    
    List<TPSOrderDetails> details;
    
    //订单类型：1-乐蜂订单, 2-海淘订单, 3-OXO订单, 4-普通订单, 5-海淘直发,6-普通直发单
    private Integer doType;
    

    public List<TPSOrderDetails> getDetails() {
        return this.details;
    }

    public void setDetails(List<TPSOrderDetails> details) {
        this.details = details;
    }

    public String getBoxNo() {
        return this.boxNo;
    }

    public void setBoxNo(String boxNo) {
        this.boxNo = boxNo;
    }

    public String getVipClub() {
        return this.vipClub;
    }

    public void setVipClub(String vipClub) {
        this.vipClub = vipClub;
    }

    public Integer getServiceType() {
        return this.serviceType;
    }

    public void setServiceType(Integer serviceType) {
        this.serviceType = serviceType;
    }

    public String getOrderDeliveryBatch() {
        return this.orderDeliveryBatch;
    }

    public void setOrderDeliveryBatch(String orderDeliveryBatch) {
        this.orderDeliveryBatch = orderDeliveryBatch;
    }


    /**
	 * @return the transportDay
	 */
	public String getTransportDay() {
		return transportDay;
	}

	/**
	 * @param transportDay the transportDay to set
	 */
	public void setTransportDay(String transportDay) {
		this.transportDay = transportDay;
	}

	public boolean isCod() {
        return this.isCod;
    }

    public void setCod(boolean isCod) {
        this.isCod = isCod;
    }

    public boolean getIsCod() {
        return this.isCod;
    }

    public void setIsCod(boolean isCod) {
        this.isCod = isCod;
    }

    public BigDecimal getOrderSum() {
        return this.orderSum;
    }

    public void setOrderSum(BigDecimal orderSum) {
        this.orderSum = orderSum;
    }

    public BigDecimal getCodAmount() {
        return this.codAmount;
    }

    public void setCodAmount(BigDecimal codAmount) {
        this.codAmount = codAmount;
    }

    public Integer getPayment() {
        return this.payment;
    }

    public void setPayment(Integer payment) {
        this.payment = payment;
    }

    public String getCustOrderNo() {
        return this.custOrderNo;
    }

    public void setCustOrderNo(String custOrderNo) {
        this.custOrderNo = custOrderNo;
    }

    public String getOrgName() {
        return this.orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    public String getOrgCode() {
        return this.orgCode;
    }

    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    public String getStoreContacts() {
        return this.storeContacts;
    }

    public void setStoreContacts(String storeContacts) {
        this.storeContacts = storeContacts;
    }

    public String getStoreTel() {
        return this.storeTel;
    }

    public void setStoreTel(String storeTel) {
        this.storeTel = storeTel;
    }

    // Property accessors
    public Integer getInfCarrierPickTaskSendId() {
        return this.infCarrierPickTaskSendId;
    }

    public void setInfCarrierPickTaskSendId(Integer infCarrierPickTaskSendId) {
        this.infCarrierPickTaskSendId = infCarrierPickTaskSendId;
    }

    public Long getRecordVersion() {
        return this.recordVersion;
    }

    public void setRecordVersion(Long recordVersion) {
        this.recordVersion = recordVersion;
    }

    /**
     * * 收件人地址
     */
    public String getBuyerAddress() {
        return this.buyerAddress;
    }

    public void setBuyerAddress(String buyerAddress) {
        this.buyerAddress = buyerAddress;
    }

    /**
     * * 电话
     */
    public String getTel() {
        return this.tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * * 手机号码
     */
    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * * 邮编
     */
    public String getPostCode() {
        return this.postCode;
    }

    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    /**
     * * 重量
     */
    public BigDecimal getOriginalWeight() {
        return this.originalWeight;
    }

    public void setOriginalWeight(BigDecimal originalWeight) {
        this.originalWeight = originalWeight;
    }

    /**
     * * 体积
     */
    public BigDecimal getOriginalVolume() {
        return this.originalVolume;
    }

    public void setOriginalVolume(BigDecimal originalVolume) {
        this.originalVolume = originalVolume;
    }

    /**
     * * 所属仓库
     */
    public String getWarehouse() {
        return this.warehouse;
    }

    public void setWarehouse(String warehouse) {
        this.warehouse = warehouse;
    }

    /**
     * * 总箱数
     */
    public Integer getTotalPack() {
        return this.totalPack;
    }

    public void setTotalPack(Integer totalPack) {
        this.totalPack = totalPack;
    }

    /**
     * * 订单客户
     */
    public String getCustomerName() {
        return this.customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * * 销售平台
     */
    public String getSalesPlatform() {
        return this.salesPlatform;
    }

    public void setSalesPlatform(String salesPlatform) {
        this.salesPlatform = salesPlatform;
    }

    /**
     * * 运输类型
     */
    public String getTransportType() {
        return this.transportType;
    }

    public void setTransportType(String transportType) {
        this.transportType = transportType;
    }

    /**
     * * 保价价值
     */
    public BigDecimal getValuationValue() {
        return this.valuationValue;
    }

    public void setValuationValue(BigDecimal valuationValue) {
        this.valuationValue = valuationValue;
    }

    /**
     * * 唯品会仓库地址
     */
    public String getWarehouseAddr() {
        return this.warehouseAddr;
    }

    public void setWarehouseAddr(String warehouseAddr) {
        this.warehouseAddr = warehouseAddr;
    }

    /**
     * * 运费
     */
    public BigDecimal getFeight() {
        return this.feight;
    }

    public void setFeight(BigDecimal feight) {
        this.feight = feight;
    }

    /**
     * * 操作指令
     */
    public String getCmdType() {
        return this.cmdType;
    }

    public void setCmdType(String cmdType) {
        this.cmdType = cmdType;
    }

    /**
     * * 业务类型
     */
    public Integer getBusinessType() {
        return this.businessType;
    }

    public void setBusinessType(Integer businessType) {
        this.businessType = businessType;
    }

    /**
     * * 是否已发送
     */
    public boolean getIsSend() {
        return this.isSend;
    }

    public void setIsSend(boolean isSend) {
        this.isSend = isSend;
    }

    /**
     * * 品牌供应商
     */
    public String getBrandName() {
        return this.brandName;
    }

    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    /**
     * * 提货门店
     */
   	public String getStoreName() {
   		return storeName;
   	}
   	
    /**
     * * 发货省
     */
    public String getCnorProv() {
        return this.cnorProv;
    }

	/**
	 * @param storeName the storeName to set
	 */
	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	public void setCnorProv(String cnorProv) {
        this.cnorProv = cnorProv;
    }

    /**
     * * 发货城市
     */
    public String getCnorCity() {
        return this.cnorCity;
    }

    public void setCnorCity(String cnorCity) {
        this.cnorCity = cnorCity;
    }

    /**
     * * 发货区
     */
    public String getCnorRegion() {
        return this.cnorRegion;
    }

    public void setCnorRegion(String cnorRegion) {
        this.cnorRegion = cnorRegion;
    }

    /**
     * * 发货相信地址
     */
    public String getCnorAddr() {
        return this.cnorAddr;
    }

    public void setCnorAddr(String cnorAddr) {
        this.cnorAddr = cnorAddr;
    }

    /**
     * * 要求提货时间
     */
    public String getRequiredTime() {
        return this.requiredTime;
    }

    public void setRequiredTime(String requiredTime) {
        this.requiredTime = requiredTime;
    }

    /**
     * * 承运商编码
     */
    public String getCustCode() {
        return this.custCode;
    }

    public void setCustCode(String custCode) {
        this.custCode = custCode;
    }

    /**
     * * 订单号
     */
    public String getOrderSn() {
        return this.orderSn;
    }

    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn;
    }

    /**
     * * 收件人
     */
    public String getBuyerName() {
        return this.buyerName;
    }

    public void setBuyerName(String buyerName) {
        this.buyerName = buyerName;
    }

    // The following is extra code specified in the hbm.xml files
    public static final TPSOrder NULL = new TPSOrder();

    private static final long serialVersionUID = 4038040015891070000L;

	/**
	 * @return the addTime
	 */
	public Long getAddTime() {
		return addTime;
	}

	/**
	 * @param addTime the addTime to set
	 */
	public void setAddTime(Long addTime) {
		this.addTime = addTime;
	}

	/**
	 * @return the createTime
	 */
	public Long getCreateTime() {
		return createTime;
	}

	/**
	 * @param createTime the createTime to set
	 */
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	/**
	 * @return the lastFetchTime
	 */
	public Long getLastFetchTime() {
		return lastFetchTime;
	}

	/**
	 * @param lastFetchTime the lastFetchTime to set
	 */
	public void setLastFetchTime(Long lastFetchTime) {
		this.lastFetchTime = lastFetchTime;
	}

	/**
	 * @return the goGetReturnTime
	 */
	public String getGoGetReturnTime() {
		return goGetReturnTime;
	}

	/**
	 * @param goGetReturnTime the goGetReturnTime to set
	 */
	public void setGoGetReturnTime(String goGetReturnTime) {
		this.goGetReturnTime = goGetReturnTime;
	}

	public Integer getIsGatherpack() {
		return isGatherpack;
	}

	public void setIsGatherpack(Integer isGatherpack) {
		this.isGatherpack = isGatherpack;
	}

	public Integer getIsGathercomp() {
		return isGathercomp;
	}

	public void setIsGathercomp(Integer isGathercomp) {
		this.isGathercomp = isGathercomp;
	}

	public Integer getDoType() {
		return doType;
	}

	public void setDoType(Integer doType) {
		this.doType = doType;
	}

}
