package cn.explink.b2c.zjfeiyuan;

public class XmlDocument {
	public static void main(String[] args) {
		String xmlStrRequest = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
				+ "<request>"
				  + "<head>"
				  + "<usercode>explink</usercode>"
				  + "<batchno>2013072312341034</batchno>"
				  + "<key>2341asd9fasdfadf23</key>"
				  + "</head>"
				  + "<items>" 
				  + 	"<item>" 
				  +      "<itemno>1></itemno>"
				  +      "<province><![CDATA[广东省]]></province>"
				  +      "<city><![CDATA[广州市]]></city>"
				  +      "<area><![CDATA[天河区]]></area>"
				  +		 "<town></town>"
				  +		 "<address><![CDATA[广东省广州市天河区天河东路118号]]></address>"
				  +		 "<yworder>1234567889</yworder>"
				  + 	"</item>" 
				  + 	"<item>" 
				  +      "<itemno>2></itemno>"
				  +      "<province><![CDATA[广东省]]></province>"
				  +      "<city><![CDATA[广州市]]></city>"
				  +      "<area><![CDATA[天河区]]></area>"
				  +		 "<town></town>"
				  +		 "<address><![CDATA[广东省广州市天河区天河东路119号]]></address>"
				  +		 "<yworder>1234567899</yworder>"
				  + 	"</item>" 
				  + "</items>" 
			    + "</request>";
		
		String xmlStrResponse = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
				  + "<response>"	
				  + "<head>"	
				  + "<msg></msg>"
				  + "</head>"	
				  + "<items>"	
				  + "<item>"	
				  + "<itemno>1></itemno>"	
				  + "<netid>101</netid>"	
				  + "<netpoint><![CDATA[天河分站]]></netpoint>"	
				  + "<yworder>1234567889</yworder>"	
				  + "<siteno>30057400</siteno>"	
				  + "<sitename><![CDATA[天河配送站]]></sitename>"	
				  + "<remark></remark>"	
				  + "</item>"	
				  + "<item>"	
				  + "<itemno>2></itemno>"	
				  + "<netid>101</netid>"	
				  + "<netpoint><![CDATA[天河分站]]></netpoint>"	
				  + "<yworder>1234567899</yworder>"	
				  + "<siteno>30057400</siteno>"	
				  + "<sitename><![CDATA[天河配送站]]></sitename>"	
				  + "<remark></remark>"	
				  + "</item>"	
				  + "</items>"	
				  + "</head>"	
				  + "</response>"	;
	}
	
}
