//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.05 at 04:03:53 PM CST 
//


package cn.explink.b2c.vipshop.oxo.request;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for request element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="request">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="head">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="request_time">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;enumeration value="2015-04-15 21:20:23"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                     &lt;element name="cust_code">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;enumeration value="FY"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="binds">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="bind" maxOccurs="unbounded">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="cust_data_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="order_sn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="pick_person">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="����"/>
 *                                     &lt;enumeration value="����"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element name="pick_person_tel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="pick_car_no">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="��A10001"/>
 *                                     &lt;enumeration value="��A10002"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element name="pick_qty" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="expected_pick_time">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="2015-08-05 15:57:00"/>
 *                                     &lt;enumeration value="2015-08-05 15:57:01"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element name="pic_url">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="test"/>
 *                                     &lt;enumeration value="test1"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element name="id_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "head",
    "binds"
})
@XmlRootElement(name = "request")
public class OXOJITFeedbackVo {

    @XmlElement(required = true)
    protected OXOJITFeedbackVo.Head head;
    @XmlElement(required = true)
    protected OXOJITFeedbackVo.Binds binds;

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link OXOJITFeedbackVo.Head }
     *     
     */
    public OXOJITFeedbackVo.Head getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link OXOJITFeedbackVo.Head }
     *     
     */
    public void setHead(OXOJITFeedbackVo.Head value) {
        this.head = value;
    }

    /**
     * Gets the value of the binds property.
     * 
     * @return
     *     possible object is
     *     {@link OXOJITFeedbackVo.Binds }
     *     
     */
    public OXOJITFeedbackVo.Binds getBinds() {
        return binds;
    }

    /**
     * Sets the value of the binds property.
     * 
     * @param value
     *     allowed object is
     *     {@link OXOJITFeedbackVo.Binds }
     *     
     */
    public void setBinds(OXOJITFeedbackVo.Binds value) {
        this.binds = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="bind" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="cust_data_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="order_sn" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="pick_person">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="����"/>
     *                         &lt;enumeration value="����"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="pick_person_tel" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="pick_car_no">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="��A10001"/>
     *                         &lt;enumeration value="��A10002"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="pick_qty" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="expected_pick_time">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="2015-08-05 15:57:00"/>
     *                         &lt;enumeration value="2015-08-05 15:57:01"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="pic_url">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="test"/>
     *                         &lt;enumeration value="test1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="id_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bind"
    })
    public static class Binds {

        @XmlElement(required = true)
        protected List<OXOJITFeedbackVo.Binds.Bind> bind;

        /**
         * Gets the value of the bind property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the bind property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBind().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OXOJITFeedbackVo.Binds.Bind }
         * 
         * 
         */
        public List<OXOJITFeedbackVo.Binds.Bind> getBind() {
            if (bind == null) {
                bind = new ArrayList<OXOJITFeedbackVo.Binds.Bind>();
            }
            return this.bind;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="cust_data_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="order_sn" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="pick_person">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="����"/>
         *               &lt;enumeration value="����"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="pick_person_tel" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="pick_car_no">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="��A10001"/>
         *               &lt;enumeration value="��A10002"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="pick_qty" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="expected_pick_time">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="2015-08-05 15:57:00"/>
         *               &lt;enumeration value="2015-08-05 15:57:01"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="pic_url">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="test"/>
         *               &lt;enumeration value="test1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="id_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "custDataId",
            "orderSn",
            "pickPerson",
            "pickPersonTel",
            "pickCarNo",
            "pickQty",
            "expectedPickTime",
            "picUrl",
            "idNumber"
        })
        public static class Bind {

            @XmlElement(name = "cust_data_id", required = true)
            protected String custDataId;
            @XmlElement(name = "order_sn", required = true)
            protected String orderSn;
            @XmlElement(name = "pick_person", required = true)
            protected String pickPerson;
            @XmlElement(name = "pick_person_tel", required = true)
            protected String pickPersonTel;
            @XmlElement(name = "pick_car_no", required = true)
            protected String pickCarNo;
            @XmlElement(name = "pick_qty", required = true)
            protected String pickQty;
            @XmlElement(name = "expected_pick_time", required = true)
            protected String expectedPickTime;
            @XmlElement(name = "pic_url", required = true)
            protected String picUrl;
            @XmlElement(name = "id_number", required = true)
            protected String idNumber;

            /**
             * Gets the value of the custDataId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCustDataId() {
                return custDataId;
            }

            /**
             * Sets the value of the custDataId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCustDataId(String value) {
                this.custDataId = value;
            }

            /**
             * Gets the value of the orderSn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOrderSn() {
                return orderSn;
            }

            /**
             * Sets the value of the orderSn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOrderSn(String value) {
                this.orderSn = value;
            }

            /**
             * Gets the value of the pickPerson property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPickPerson() {
                return pickPerson;
            }

            /**
             * Sets the value of the pickPerson property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPickPerson(String value) {
                this.pickPerson = value;
            }

            /**
             * Gets the value of the pickPersonTel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPickPersonTel() {
                return pickPersonTel;
            }

            /**
             * Sets the value of the pickPersonTel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPickPersonTel(String value) {
                this.pickPersonTel = value;
            }

            /**
             * Gets the value of the pickCarNo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPickCarNo() {
                return pickCarNo;
            }

            /**
             * Sets the value of the pickCarNo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPickCarNo(String value) {
                this.pickCarNo = value;
            }

            /**
             * Gets the value of the pickQty property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPickQty() {
                return pickQty;
            }

            /**
             * Sets the value of the pickQty property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPickQty(String value) {
                this.pickQty = value;
            }

            /**
             * Gets the value of the expectedPickTime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExpectedPickTime() {
                return expectedPickTime;
            }

            /**
             * Sets the value of the expectedPickTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExpectedPickTime(String value) {
                this.expectedPickTime = value;
            }

            /**
             * Gets the value of the picUrl property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPicUrl() {
                return picUrl;
            }

            /**
             * Sets the value of the picUrl property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPicUrl(String value) {
                this.picUrl = value;
            }

            /**
             * Gets the value of the idNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIdNumber() {
                return idNumber;
            }

            /**
             * Sets the value of the idNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIdNumber(String value) {
                this.idNumber = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="request_time">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="2015-04-15 21:20:23"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="cust_code">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="FY"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "version",
        "requestTime",
        "custCode"
    })
    public static class Head {

        @XmlElement(required = true)
        protected String version;
        @XmlElement(name = "request_time", required = true)
        protected String requestTime;
        @XmlElement(name = "cust_code", required = true)
        protected String custCode;

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

        /**
         * Gets the value of the requestTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequestTime() {
            return requestTime;
        }

        /**
         * Sets the value of the requestTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRequestTime(String value) {
            this.requestTime = value;
        }

        /**
         * Gets the value of the custCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustCode() {
            return custCode;
        }

        /**
         * Sets the value of the custCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustCode(String value) {
            this.custCode = value;
        }

    }

}
