-- 创建表fn_station_sign_order_details_snapshot_express
CREATE TABLE `fn_station_sign_order_details_snapshot_express` (
  `id` bigint(10) NOT NULL AUTO_INCREMENT,
  `cwb` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '订单号',
  `receivablefee` decimal(19,2) DEFAULT '0.00' COMMENT '应收金额',
  `paybackfee` decimal(19,2) DEFAULT '0.00' COMMENT '应退金额',
  `customerid` int(11) DEFAULT '-1' COMMENT '客户编号',
  `cwbordertypeid` varchar(11) COLLATE utf8_bin DEFAULT '-1' COMMENT '订单类型',
  `flowordertype` int(11) DEFAULT '0' COMMENT '订单操作状态',
  `deliverybranchid` int(11) DEFAULT '0' COMMENT '配送站点',
  `instationid` int(11) DEFAULT NULL COMMENT '揽件入站站点id',
  `cwbstate` int(11) DEFAULT '1' COMMENT '订单状态',
  `deliverystate` int(11) DEFAULT '0' COMMENT '反馈状态',
  `shouldfare` decimal(9,2) DEFAULT '0.00' COMMENT '应收运费',
  `infactfare` decimal(9,2) DEFAULT '0.00' COMMENT '实收运费',
  `packagefee` decimal(19,2) DEFAULT '0.00' COMMENT '包装费用（元）',
  `insuredfee` decimal(19,2) DEFAULT '0.00' COMMENT '保价费用（元）',
  `totalfee` decimal(19,2) DEFAULT '0.00' COMMENT '费用合计（运费+包装+保价）',
  `newpaywayid` VARCHAR(20) COLLATE utf8_bin DEFAULT '1' COMMENT '实际支付方式',
  `sign_time` VARCHAR(50) COLLATE utf8_bin DEFAULT '' COMMENT '签收时间',
  `auditingtime` VARCHAR(50) COLLATE utf8_bin DEFAULT '' COMMENT '审核时间',
  `paymethod` int(1) DEFAULT '1' COMMENT '付款方式（0：月结，1：现付，2：到付）',
  `deliveryid` int(11) DEFAULT '0' COMMENT '派件员',
  `collectorid` int(11) DEFAULT '0' COMMENT '揽件员id',
  `instationdatetime` datetime DEFAULT NULL COMMENT '入站时间',
  `fnorgoffsetflag` int(11) DEFAULT '0' COMMENT '收款状态',
  `fnorgfreightoffsetflag` tinyint(4) DEFAULT '0' COMMENT '运费收款状态',
  `fnorgbillid` bigint(20) DEFAULT '0' COMMENT '站点账单的id',
  `fnorgfreightbillid` bigint(20) DEFAULT '0' COMMENT '站点运费账单的id',
  `reportid` bigint(20) DEFAULT '-1' COMMENT '报表id',
  `state` int(11) DEFAULT '1' COMMENT '记录状态',
  `reportdate` int(11) NOT NULL COMMENT '生命周期报表日期',
  `createtime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建更新时间',
  PRIMARY KEY (`id`),
  KEY `express_order_snapshot_cwb_idx` (`cwb`),
  KEY `express_order_snapshot_deliverybranchid_idx` (`deliverybranchid`),
  KEY `express_order_snapshot_instationid_idx` (`instationid`),
  KEY `express_order_snapshot_deliveryid_idx` (`deliveryid`),
  KEY `express_order_snapshot_collectorid_idx` (`collectorid`),
  KEY `express_order_snapshot_rpt_date_idx` (`reportdate`)
) ENGINE=InnoDB AUTO_INCREMENT=308 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- 修改表fn_station_sign_order_details_snapshot
ALTER TABLE `fn_station_sign_order_details_snapshot`   
  ADD COLUMN `instationid` INT(11) DEFAULT NULL COMMENT '揽件入站站点id',
  ADD COLUMN `packagefee` DECIMAL(19,2) DEFAULT '0.00' COMMENT '包装费用（元）',
  ADD COLUMN `insuredfee` DECIMAL(19,2) DEFAULT '0.00' COMMENT '保价费用（元）',
  ADD COLUMN `totalfee` DECIMAL(19,2) DEFAULT '0.00' COMMENT '费用合计（运费+包装+保价）',
  ADD COLUMN `paymethod` INT(1) DEFAULT '3' COMMENT '付款方式（0：月结，1：现付，2：到付）',
  ADD COLUMN `collectorid` INT(11) DEFAULT '0' COMMENT '揽件员id',
  ADD COLUMN `instationdatetime` DATETIME DEFAULT NULL COMMENT '入站时间',
  ADD  INDEX `order_snapshot_deliveryid_idx` (`deliveryid`);